spring:
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 256MB
      max-file-size: 256MB
  application:
    name: PRODUCT-SERVICE
  data:
    mongodb:
      database: sellit
      port: '27017'
      host: localhost
server:
  port: '9095'
